### ISSUE TITLE
如何修改row-height，虚拟滚动下也能生效

### ISSUE THREAD

**Issue by frankie-zeng** [fall-zhang/vue-fantable#8]
fan-table 的版本：
0.2.4
vue 的版本：
3.4.x
使用的浏览器：
chorme
问题的类型（issue or feature）：
如何修改row height， 修改css的--fan-table-body-row-height 不管用。
对问题的详细说明：

**Comment by fall-zhang** [comment]
row height 是通过 CSS 变量 `--fan-table-body-row-height: 40px;` 设置的，你可以添加以下样式实现更改行高。
```css
.fan-table{
  --fan-table-body-row-height: 60px
}
```
